
import type { Appointment } from './data';

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    studentId: 'student1',
    studentName: 'John Doe',
    studentEmail: 'john.doe@example.com',
    studentIdNumber: 'S-2024-001',
    contactNumber: '123-456-7890',
    serviceId: 'sog',
    serviceName: 'SOG',
    appointmentDateTime: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    status: 'Confirmed',
    documentUrl: 'https://example.com/document1.pdf',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    studentId: 'student2',
    studentName: 'Jane Smith',
    studentEmail: 'jane.smith@example.com',
    studentIdNumber: 'S-2024-002',
    contactNumber: '098-765-4321',
    serviceId: 'prospectus-evaluation',
    serviceName: 'Prospectus Evaluation',
    appointmentDateTime: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    status: 'Pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    studentId: 'student3',
    studentName: 'Peter Jones',
    studentEmail: 'peter.jones@example.com',
    studentIdNumber: 'S-2024-003',
    contactNumber: '555-555-5555',
    serviceId: 'sog',
    serviceName: 'SOG',
    appointmentDateTime: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    status: 'Completed',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    studentId: 'student4',
    studentName: 'Mary Williams',
    studentEmail: 'mary.williams@example.com',
    studentIdNumber: 'S-2024-004',
    contactNumber: '111-222-3333',
    serviceId: 'prospectus-evaluation',
    serviceName: 'Prospectus Evaluation',
    appointmentDateTime: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    status: 'Cancelled',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    studentId: 'student1',
    studentName: 'John Doe',
    studentEmail: 'john.doe@example.com',
    studentIdNumber: 'S-2024-001',
    contactNumber: '123-456-7890',
    serviceId: 'prospectus-evaluation',
    serviceName: 'Prospectus Evaluation',
    appointmentDateTime: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    status: 'Pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
